// Fallback data for when database is unavailable (e.g., Vercel serverless)

export const fallbackTemplates = [
  {
    id: '1',
    title: 'Business Pro',
    description: 'A sleek, modern template designed for corporate websites and business portfolios. Features clean layouts, professional typography, and conversion-optimized landing pages.',
    category: 'Business',
    image: '/images/template-business.png',
    features: JSON.stringify(['Responsive Design', 'SEO Optimized', 'Contact Forms', 'Analytics Integration', 'Multi-page Layout', 'Newsletter Signup']),
    industries: JSON.stringify(['Consulting', 'Finance', 'Insurance', 'Real Estate']),
    featured: true,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Creative Portfolio',
    description: 'Showcase your creative work with this stunning portfolio template. Features elegant gallery layouts, smooth animations, and a minimalist aesthetic.',
    category: 'Portfolio',
    image: '/images/template-portfolio.png',
    features: JSON.stringify(['Image Gallery', 'Video Support', 'Smooth Animations', 'Project Pages', 'About Section', 'Client Testimonials']),
    industries: JSON.stringify(['Photography', 'Design', 'Art', 'Freelance']),
    featured: true,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'ShopFront',
    description: 'Launch your online store with this feature-rich e-commerce template. Complete with product pages, shopping cart, and seamless checkout flow.',
    category: 'E-commerce',
    image: '/images/template-ecommerce.png',
    features: JSON.stringify(['Product Catalog', 'Shopping Cart', 'Secure Checkout', 'Inventory Management', 'Customer Reviews', 'Payment Integration']),
    industries: JSON.stringify(['Retail', 'Fashion', 'Electronics', 'Food & Beverage']),
    featured: true,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'Blog Master',
    description: 'A clean, content-focused blog template with beautiful typography, reading modes, and social sharing capabilities.',
    category: 'Blog',
    image: '/images/template-saas.png',
    features: JSON.stringify(['Content Management', 'Categories & Tags', 'Social Sharing', 'Comments System', 'Search Functionality', 'RSS Feed']),
    industries: JSON.stringify(['Media', 'Publishing', 'Personal Blog', 'News']),
    featured: false,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'SaaS Dashboard',
    description: 'Perfect for SaaS products and web applications. Includes dashboard layouts, data visualization components, and user management interfaces.',
    category: 'SaaS',
    image: '/images/template-saas.png',
    features: JSON.stringify(['Dashboard Layout', 'Data Visualization', 'User Management', 'API Integration', 'Authentication', 'Billing Pages']),
    industries: JSON.stringify(['Technology', 'Startups', 'Fintech', 'HealthTech']),
    featured: true,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '6',
    title: 'Corporate Elite',
    description: 'A premium corporate template with professional layouts, team pages, and service showcases. Ideal for established businesses.',
    category: 'Business',
    image: '/images/template-business.png',
    features: JSON.stringify(['Team Pages', 'Service Showcases', 'Case Studies', 'Client Portal', 'Multi-language', 'CRM Integration']),
    industries: JSON.stringify(['Enterprise', 'Legal', 'Healthcare', 'Education']),
    featured: false,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '7',
    title: 'Restaurant Hub',
    description: 'A delicious template for restaurants and cafes. Features menu displays, reservation systems, and mouth-watering gallery layouts.',
    category: 'Business',
    image: '/images/template-ecommerce.png',
    features: JSON.stringify(['Menu Display', 'Online Reservations', 'Photo Gallery', 'Location Map', 'Opening Hours', 'Online Ordering']),
    industries: JSON.stringify(['Restaurant', 'Cafe', 'Bakery', 'Catering']),
    featured: false,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '8',
    title: 'TechLaunch',
    description: 'A cutting-edge template for tech startups and product launches. Features bold hero sections, feature grids, and pricing tables.',
    category: 'SaaS',
    image: '/images/template-portfolio.png',
    features: JSON.stringify(['Landing Pages', 'Feature Grid', 'Pricing Tables', 'Waitlist Signup', 'Product Demo', 'Documentation']),
    industries: JSON.stringify(['AI & ML', 'Blockchain', 'Cloud Services', 'DevTools']),
    featured: false,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '9',
    title: 'EduMentor — Course Platform',
    description: 'A comprehensive e-learning platform template for selling online courses. Features include course pages with video previews, interactive syllabus with accordion modules, quiz system with instant feedback, progress tracking with timers, instructor profiles, and a complete Material Design system built with Tailwind CSS. Perfect for online academies, training centers, and educational institutions.',
    category: 'Education',
    image: '/images/template-education.png',
    previewUrl: '/templates/edumentor-course-platform.html',
    features: JSON.stringify(['Video Course Player', 'Interactive Syllabus', 'Quiz System', 'Progress Tracking', 'Student Dashboard', 'Instructor Profiles', 'Responsive Design', 'Material Design System', 'Accordion Modules', 'Timer & Countdown']),
    industries: JSON.stringify(['Education', 'E-Learning', 'Training', 'Academy', 'Online Courses', 'Corporate Training']),
    livePreview: '/templates/edumentor-course-platform.html',
    featured: true,
    active: true,
    createdAt: new Date().toISOString(),
  },
]

export const fallbackPlans = [
  {
    id: 'plan-1',
    name: 'Monthly',
    price: 30,
    currency: 'USD',
    interval: 'monthly',
    features: JSON.stringify([
      'Professional website design',
      'Responsive mobile layout',
      'SSL certificate included',
      'Free domain (1 year)',
      '5 GB hosting storage',
      'Monthly design updates',
      'Email support',
      'Basic SEO optimization',
    ]),
    popular: false,
    active: true,
  },
  {
    id: 'plan-2',
    name: 'Semi-Annual',
    price: 160,
    currency: 'USD',
    interval: 'semi_annual',
    features: JSON.stringify([
      'Everything in Monthly, plus:',
      'Priority design revisions',
      'Custom domain setup',
      '20 GB hosting storage',
      'Bi-monthly design updates',
      'Priority email support',
      'Advanced SEO optimization',
      'Save $20 vs monthly',
    ]),
    popular: false,
    active: true,
  },
  {
    id: 'plan-3',
    name: 'Annual',
    price: 300,
    currency: 'USD',
    interval: 'annual',
    features: JSON.stringify([
      'Everything in Semi-Annual, plus:',
      '50 GB hosting storage',
      'Weekly design updates',
      'Priority 24/7 support',
      'Advanced SEO & analytics',
      'E-commerce integration',
      'Database setup & management',
      'Dedicated project manager',
      '2 months free',
    ]),
    popular: true,
    active: true,
  },
]

export const fallbackTestimonials = [
  {
    id: 't1',
    name: 'Sarah Johnson',
    role: 'CEO',
    company: 'TechStart Inc.',
    content: 'WebFlowSub transformed our online presence completely. The subscription model makes it affordable and the design quality is outstanding. Highly recommend!',
    rating: 5,
    active: true,
  },
  {
    id: 't2',
    name: 'Michael Chen',
    role: 'Marketing Director',
    company: 'GrowthLab',
    content: "We switched from a one-time design agency to WebFlowSub and couldn't be happier. The ongoing support and regular updates keep our site fresh and modern.",
    rating: 5,
    active: true,
  },
  {
    id: 't3',
    name: 'Emily Rodriguez',
    role: 'Founder',
    company: 'Bloom Studio',
    content: 'As a small business owner, I needed a professional website without breaking the bank. WebFlowSub delivered beyond my expectations with their annual plan.',
    rating: 5,
    active: true,
  },
  {
    id: 't4',
    name: 'David Park',
    role: 'CTO',
    company: 'InnovateTech',
    content: 'The technical quality of the websites is impressive. Fast loading times, perfect SEO scores, and the database integration was seamless. Great value for money.',
    rating: 4,
    active: true,
  },
]

export const fallbackFaqs = [
  {
    id: 'f1',
    question: 'How does the subscription model work?',
    answer: 'Our subscription model provides you with a professionally designed website for a monthly or annual fee. This includes hosting, maintenance, design updates, and technical support. You can cancel anytime with our flexible plans.',
    order: 1,
    active: true,
  },
  {
    id: 'f2',
    question: "What's included in the website design?",
    answer: 'Every subscription includes a custom-designed website based on your chosen template, responsive mobile layouts, SSL certificate, domain setup, SEO optimization, and ongoing maintenance. Annual plans also include priority support and e-commerce integration.',
    order: 2,
    active: true,
  },
  {
    id: 'f3',
    question: 'Can I switch between plans?',
    answer: "Yes! You can upgrade or downgrade your plan at any time. When upgrading, you'll get immediate access to additional features. When downgrading, changes take effect at the start of your next billing cycle.",
    order: 3,
    active: true,
  },
  {
    id: 'f4',
    question: 'How long does it take to build my website?',
    answer: 'Typically, we deliver your initial website within 5-7 business days after receiving your requirements. Complex projects with e-commerce or custom features may take up to 14 business days.',
    order: 4,
    active: true,
  },
  {
    id: 'f5',
    question: 'Do I own the website design?',
    answer: 'While you have full usage rights to your website as long as your subscription is active, the underlying template designs remain our intellectual property. If you cancel, you can export your content at any time.',
    order: 5,
    active: true,
  },
  {
    id: 'f6',
    question: 'What happens if I cancel my subscription?',
    answer: 'If you cancel, your website will remain active until the end of your current billing period. After that, we provide a 30-day grace period to export your data. You can reactivate your subscription at any time.',
    order: 6,
    active: true,
  },
]

export const fallbackSocialLinks = [
  { id: 's1', platform: 'facebook', url: 'https://facebook.com/webflowsub', order: 1, active: true },
  { id: 's2', platform: 'twitter', url: 'https://twitter.com/webflowsub', order: 2, active: true },
  { id: 's3', platform: 'instagram', url: 'https://instagram.com/webflowsub', order: 3, active: true },
  { id: 's4', platform: 'linkedin', url: 'https://linkedin.com/company/webflowsub', order: 4, active: true },
  { id: 's5', platform: 'youtube', url: 'https://youtube.com/@webflowsub', order: 5, active: true },
]
