// Fallback data for when database is unavailable (e.g., Vercel serverless)

export const fallbackTemplates = [
  {
    id: '9',
    title: 'EduMentor — Course Platform',
    description: 'A comprehensive e-learning platform template for selling online courses. Features include course pages with video previews, interactive syllabus with accordion modules, quiz system with instant feedback, progress tracking with timers, instructor profiles, and a complete Material Design system built with Tailwind CSS. Perfect for online academies, training centers, and educational institutions.',
    category: 'Education',
    image: '/images/template-education.png',
    previewUrl: '/templates/edumentor-course-platform.html',
    features: JSON.stringify(['Video Course Player', 'Interactive Syllabus', 'Quiz System', 'Progress Tracking', 'Student Dashboard', 'Instructor Profiles', 'Responsive Design', 'Material Design System', 'Accordion Modules', 'Timer & Countdown']),
    industries: JSON.stringify(['Education', 'E-Learning', 'Training', 'Academy', 'Online Courses', 'Corporate Training']),
    livePreview: '/templates/edumentor-course-platform.html',
    featured: true,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '10',
    title: 'Nexus — Multi-Purpose Business',
    description: 'A versatile, multi-purpose business template designed for agencies, startups, and enterprises. Features a stunning animated hero with live dashboard mockup, filterable portfolio grid, 4-step process timeline, interactive FAQ accordion, 3-tier pricing cards, testimonial tabs, contact modal with form, and smooth scroll navigation. Built with Tailwind CSS, custom animations, glass morphism effects, and fully responsive design. Perfect for creative agencies, consulting firms, SaaS companies, and any business that wants a professional online presence.',
    category: 'Business',
    image: '/images/template-nexus.png',
    previewUrl: '/templates/nexus-multi-purpose.html',
    features: JSON.stringify(['Animated Hero with Dashboard Mockup', 'Filterable Portfolio Grid', '4-Step Process Timeline', 'Interactive FAQ Accordion', '3-Tier Pricing Cards', 'Testimonial Tabs System', 'Contact Modal with Form', 'Animated Counters', 'Glass Morphism Design', 'Smooth Scroll Navigation', 'Mobile Menu', 'Toast Notifications', 'Fully Responsive', 'Custom CSS Animations']),
    industries: JSON.stringify(['Agency', 'Startup', 'Consulting', 'SaaS', 'E-Commerce', 'Real Estate', 'Healthcare', 'Finance', 'Technology', 'Marketing']),
    livePreview: '/templates/nexus-multi-purpose.html',
    featured: true,
    active: true,
    createdAt: new Date().toISOString(),
  },
]

export const fallbackPlans = [
  {
    id: 'plan-1',
    name: 'Monthly',
    price: 30,
    currency: 'USD',
    interval: 'monthly',
    features: JSON.stringify([
      'Professional website design',
      'Responsive mobile layout',
      'SSL certificate included',
      'Free domain (1 year)',
      '5 GB hosting storage',
      'Monthly design updates',
      'Email support',
      'Basic SEO optimization',
    ]),
    popular: false,
    active: true,
  },
  {
    id: 'plan-2',
    name: 'Semi-Annual',
    price: 160,
    currency: 'USD',
    interval: 'semi_annual',
    features: JSON.stringify([
      'Everything in Monthly, plus:',
      'Priority design revisions',
      'Custom domain setup',
      '20 GB hosting storage',
      'Bi-monthly design updates',
      'Priority email support',
      'Advanced SEO optimization',
      'Save $20 vs monthly',
    ]),
    popular: false,
    active: true,
  },
  {
    id: 'plan-3',
    name: 'Annual',
    price: 300,
    currency: 'USD',
    interval: 'annual',
    features: JSON.stringify([
      'Everything in Semi-Annual, plus:',
      '50 GB hosting storage',
      'Weekly design updates',
      'Priority 24/7 support',
      'Advanced SEO & analytics',
      'E-commerce integration',
      'Database setup & management',
      'Dedicated project manager',
      '2 months free',
    ]),
    popular: true,
    active: true,
  },
]

export const fallbackTestimonials = [
  {
    id: 't1',
    name: 'Sarah Chen',
    role: 'Small Business Owner',
    company: null,
    content: 'WebForge transformed my online presence completely. The subscription model makes it affordable and the design quality is outstanding. Highly recommend!',
    rating: 5,
    active: true,
  },
  {
    id: 't2',
    name: 'James Okonkwo',
    role: 'Freelance Designer',
    company: null,
    content: "As a designer myself, I appreciate the attention to detail. The templates are beautiful and the support team is incredibly responsive. Worth every penny.",
    rating: 5,
    active: true,
  },
  {
    id: 't3',
    name: 'Maya Patel',
    role: 'Boutique Owner',
    company: null,
    content: 'I was hesitant about the monthly cost at first, but the value is incredible. My website looks professional and I never have to worry about updates.',
    rating: 5,
    active: true,
  },
  {
    id: 't4',
    name: 'David Park',
    role: 'Restaurant Manager',
    company: null,
    content: 'Our reservations doubled after launching with WebForge. The team understood our vision and delivered exactly what we needed. Fantastic service.',
    rating: 5,
    active: true,
  },
]

export const fallbackFaqs = [
  {
    id: 'f1',
    question: 'How does the subscription model work?',
    answer: 'Our subscription model provides you with a professionally designed website for a monthly, semi-annual, or annual fee. This includes hosting, maintenance, design updates, and technical support. You can cancel anytime with our flexible plans.',
    order: 1,
    active: true,
  },
  {
    id: 'f2',
    question: "What's included in the website design?",
    answer: 'Every subscription includes a custom-designed website based on your chosen template, responsive mobile layouts, SSL certificate, domain setup, and SEO optimization.',
    order: 2,
    active: true,
  },
  {
    id: 'f3',
    question: 'Can I switch between plans?',
    answer: 'Yes! You can upgrade or downgrade your plan at any time.',
    order: 3,
    active: true,
  },
  {
    id: 'f4',
    question: 'How long does it take to build my website?',
    answer: 'Typically, we deliver your initial website within 5-7 business days after receiving your requirements. Complex projects with e-commerce or custom features may take up to 14 business days.',
    order: 4,
    active: true,
  },
  {
    id: 'f5',
    question: 'Do I own the website design?',
    answer: 'While you have full usage rights to your website as long as your subscription is active, the underlying template designs remain our intellectual property. If you cancel, you can export your content at any time.',
    order: 5,
    active: true,
  },
  {
    id: 'f6',
    question: 'What happens if I cancel my subscription?',
    answer: 'If you cancel, your website will remain active until the end of your current billing period. After that, we provide a 30-day grace period to export your data. You can reactivate your subscription at any time. Additionally, you have the right to download your site data after the first year from creating the site, or pay the difference for the first year design and preparation fees — in which case the client receives the site files + domain + ownership transfer.',
    order: 6,
    active: true,
  },
]

export const fallbackSocialLinks = [
  { id: 's1', platform: 'facebook', url: 'https://facebook.com/webforge', order: 1, active: true },
  { id: 's2', platform: 'twitter', url: 'https://twitter.com/webforge', order: 2, active: true },
  { id: 's3', platform: 'instagram', url: 'https://instagram.com/webforge', order: 3, active: true },
  { id: 's4', platform: 'linkedin', url: 'https://linkedin.com/company/webforge', order: 4, active: true },
  { id: 's5', platform: 'youtube', url: 'https://youtube.com/@webforge', order: 5, active: true },
]
